### ISSUE TITLE
Add accuracy attributes?

### ISSUE THREAD

**Issue by psiborg** [tessel/gps-a2235h#31]
Is it possible to add **accuracy** attributes for altitude, latitude and longitude similar to the W3C geolocation spec (https://www.w3.org/TR/geolocation-API/#coordinates_interface)? These values are usually specified in meters.

**Comment by johnnyman727** [comment]
@psiborg the GPS module on the PCB emits NMEA data which doesn't include any accuracy fields. If we implemented #32, we could have access to an HDOP (dilution of precision) which is an indicator of accuracy. For now, you could potentially use number of satellites in view as a rough indicator of accuracy.

**Comment by psiborg** [comment]
@johnnyman727 Thanks for the info. I'll try your workaround with number of satellites.
