### ISSUE TITLE
Improper coordinate parsing

### ISSUE THREAD

**Issue by ekolker** [tessel/gps-a2235h#8]
Running the example with debug mode on I get the following, which implies that we're putting the decimal point in the wrong place in our coordinate parser:

```
  Packet         $GPRMC,183810.035,A,3752.0573,N,12217.4401,W,4.82,235.69,030614,,,A*78
Lat: [ 375, 1.9803, 'N' ]       Lon: [ 122, 17.5092, 'W' ]      Timestamp: 183749.034
```

**Comment by johnnyman727** [comment]
Will be fixed with #22.
